[package]
name = "evasendesign-microstock-manager"
version = "0.1.0"
edition = "2021"

[lib]
name = "evasendesign_microstock_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "evasendesign-microstock-manager"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
