
import './style.css';
const agencies=[
'Adobe Stock','Shutterstock','Dreamstime','iStock','Pond5','Alamy','Freepik',
'Vecteezy','Canva','VideoHive / Envato','Depositphotos','IconScout','123RF','MotionElements'
];
document.querySelector('#app').innerHTML=`
<div class="app">
<header><h1>EVASENDESIGN MICROSTOCK MANAGER</h1><p>Batch upload manager • metadata • queue • agency connectors</p></header>
<section class="hero"><div><b>0</b><span>FILES</span></div><div><b>0</b><span>READY</span></div><div><b>0</b><span>SUBMITTED</span></div><div><b>0</b><span>FAILED</span></div></section>
<section class="panel"><h2>Agencies</h2><div class="grid">${agencies.map((a,i)=>`<label><input type="checkbox" checked> ${a}</label>`).join('')}</div>
<button id="upload">UPLOAD / QUEUE ALL</button></section>
<section class="panel"><h2>Build status</h2><p>Windows installer is generated by GitHub Actions. This starter uses only permitted API/FTP/official mechanisms; it does not bypass CAPTCHA or platform security.</p>
<div class="log" id="log">Ready.</div></section>
</div>`;
document.querySelector('#upload').onclick=()=>document.querySelector('#log').textContent='Queue created. Connectors are modular and agency-specific.';
